#!/usr/bin/with-contenv sh

run(){
    eval "su - nginx -s /bin/ash -c 'cd /var/www/drupal/ && "$@"'" 
    return $? 
}

if [ -f /tmp/civicrm ] && [ $(cat /tmp/civicrm) -eq 0 ]
then
    run vendor/bin/drush -u ${ADMIN_USERNAME} civicrm-api job.execute
fi
